name: Deploy Serverless App

on:
  push:
    branches:
      - main
    paths:
      - serverless/**
  pull_request:

env:
  applicationfolder: serverless/hello-lambda
  AWS_REGION: us-east-1
  S3BUCKET: githubcodedeployec2-webappdeploymentbucket-1w9iiu65ed1yn

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository

      - uses: aws-actions/setup-sam@v2
        name: Setup AWS SAM
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - run: sam build --use-container
        working-directory: ${{ env.applicationfolder }}
        name: SAM Build
      
    deploy:
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name GHAServerless --s3-bucket ${{ env.S3BUCKET }} --capabilities CAPABILITY_IAM
        working-directory: ${{ env.applicationfolder }}
        name: SAM Deploy
  